# Generated by Django 6.0.3 on 2026-03-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(max_length=150),
        ),
    ]
