# Generated by Django 6.0.3 on 2026-03-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_alter_doctor_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
