# Generated by Django 6.0.3 on 2026-03-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_doctor_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled by Patient', 'Cancelled by Patient'), ('Cancelled by Doctor', 'Cancelled by Doctor')], default='Booked', max_length=30),
        ),
    ]
