# Generated by Django 6.0.3 on 2026-03-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_appointment_appointment_mode_appointment_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='problem_category',
            field=models.CharField(choices=[('General Checkup', 'General Checkup'), ('Fever / Cold', 'Fever / Cold'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Orthopedic', 'Orthopedic'), ('Gynecology', 'Gynecology'), ('ENT', 'ENT'), ('Other', 'Other')], default='General Checkup', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='urgency_level',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
