# Generated by Django 6.0.3 on 2026-03-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0007_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Arrived', 'Arrived'), ('Waiting', 'Waiting'), ('In Consultation', 'In Consultation'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled by Patient', 'Cancelled by Patient'), ('Cancelled by Doctor', 'Cancelled by Doctor')], default='Booked', max_length=30),
        ),
    ]
