# Generated by Django 6.0.3 on 2026-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='branch_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='receptionist_profiles/'),
        ),
    ]
