# Generated by Django 6.0.3 on 2026-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0010_doctor_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicines',
            new_name='prescription_text',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='diagnosis',
            new_name='symptoms_snapshot',
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
