# Generated by Django 6.0.3 on 2026-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0013_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
