# Generated by Django 6.0.3 on 2026-03-17 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0014_prescription_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_prescription', models.FileField(blank=True, null=True, upload_to='report_show/prescriptions/')),
                ('report_note', models.TextField(blank=True, null=True)),
                ('submitted_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='Pending', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to='hms.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to='hms.patient')),
                ('previous_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reports', to='hms.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='ReportShowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_show/files/')),
                ('report_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hms.reportshow')),
            ],
        ),
    ]
