# Generated by Django 6.0.3 on 2026-03-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0015_reportshow_reportshowfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('organization_name', models.CharField(max_length=150)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.receptionist')),
            ],
        ),
        migrations.CreateModel(
            name='TestReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.medicaltest')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hms.testreport')),
            ],
        ),
    ]
